import Link from "next/link"
import { ArrowLeft, FileText } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export default function TermsOfServicePage() {
  const termsData = {
    header: {
      title: "Terms and Conditions",
      subtitle: "Complete legal terms and conditions",
      lastUpdated: "September 2025"
    },
    sections: [
      {
        title: "ChatGPT & OpenAI Integration",
        content: `The App integrates OpenAI API (https://beta.openai.com/docs/api-reference).

API terms & policies are available at https://openai.com/api/policies/service-terms/.

When you share your User Content* you agree to comply with the terms of OpenAI Sharing & Publication Policy.
User Content is any content generated by AI via the App, as well as your input content.

-The responses are generated with Chat GPT 3-5 Turbo / GPT4o, Each answer is individually generated for each user, and they are not stored by us.

-The images are analyzed with OpenAI's vision technology. Your images are sent for analysis as anonymous and are received as anonymous. At no point are the images linked to your identity.`
      },
      {
        title: "General Scope and Agreement",
        content: `The following terms and conditions (T&C) govern the relationship between you as a client and our company while interacting through our website https://voice-shopping-list.com and/or on our application BuyVoice.

Navigating and/or interacting on our website and/or application means that you expressly agree to these T&C without reserve or objection.

Our company has the right to modify or to adapt these T&C at any time and without prior notice. These T&C are directly applicable as soon as they are published on our website and/or application and/or sent to you by any means.

Please read these Terms and Conditions carefully before using, interacting or accessing our website and/or application.

By agreeing to these T&C you grant us that you have reached at least the legal majority in your country, state or province of residence. If you are a minor you grant us that you have all the rights and consent from your legal representatives to use our services. If you have not reached the legal majority then you must not use our Services.

You are not entitled to use our services, website and/or application for any illegal or unauthorized purposes.

You must not try to hack, alter the use or functions of our services, send viruses or lead or try to lead any other kind of attack towards our services. You must not try to attempt at our services' integrity either.`
      },
      {
        title: "Content and Intellectual Property",
        content: `The content provided in our Services might be accessible for free or not. Some content might be required to be logged in or to have a valid paid subscription (IAP, restricted contents or sections).

The contents of our Services are intended for personal, non-commercial use. All materials available on our Services are protected by copyrights and/or intellectual property rights.

In addition to that some content might be protected by some other rights such as, trademark, patents, trade secrets, database right, sui generis rights and other intellectual or proprietary rights.

The user of our Services is not allowed to reproduce totally or partially any content that is made available through our Services. The user will also not reproduce any of our logo, name, visual identity and so on, he will also not try to reproduce, copy or produce mere copy of our Services.

The user will not modify, copy, paste, translate, sell, exploit or transmit for free or not any of the content, text, photo, pictures, drawing, audio content, podcast or any content that is available on our Services.`
      },
      {
        title: "Subscription and Payment",
        content: `Price

The applicable subscription fees are shown before concluding the ordering process.

Please check how the Apple Store and the Google Store handle tax management and prices.

Any changes in taxes will be directly applicable to the subscriptions.

Regarding fee changes or modification, our company reserves the right to change any fee or tariff at any time and without prior notice.

Payment and Fees

Available payment methods will be shown to the client upon subscription, electronic payment will be shown only if available.

Payment methods can vary.

All of your banking details, credit card details and other payment methods are encrypted and are never stored on our website and/or application. We use third-party solutions to process your payment.

We reserve the right to modify at any time any fees, if you do not agree with the price change you can stop using our Services at any time before renewal payment occurs.

In App Purchases (IAP) to access restricted content

If you have subscribed through a third party such as Google Play, Apple App Store or any other third party, these Terms and Conditions might not apply to you. In that case you contract for such products will be with the third party and not with our Company.

Our Company will not be liable for any claims related to purchases made through a third party, you must contact that third party directly.

Our Company will have no liability or responsibility regarding any issues or difficulties regarding IAP purchases as they are done through third-party platforms.

Restoring your subscription, digital contents or In App Purchases

If you have made In App Purchases (IAP) through a third party you might be able to restore your previous purchases that you have already made. This can be done using the link within our Application and/or website.`
      },
      {
        title: "Registration Process",
        content: `Our company might or might not require our client to first register to enable the client to access some part or the whole application and/or website.

Each registration is intended for one user only and you are prohibited from sharing your credentials or your account with anyone.

We may cancel or suspend your access to our Services if you share your credentials.

Please notify us immediately at info@lweb.ch if you think that your credentials are compromised.

Registration

If registration is required to access our website and/or application then the client must first enroll itself by creating an account. To do so the client must fill in the registry form available on our website and/or application. The client will choose a login and a password linked to a valid email address.

By doing so the client agrees that he will keep his credential confidential, secure at all times and that he will not communicate them to any third-party.

The client must keep its credential confidential at all times and must not share its credentials with anyone.

Our company will not be held liable or responsible for any unauthorized use, modification or access on the client's account even if fraudulent access is made using the client's account or banking details.

Signing In with third parties authentication, including but not limited to, « Sign-in with Apple », Facebook and Twitter authentication

These third-party services might be implemented within our application and/or website to help you sign-in alongside creating an account directly on our Services.

You can either choose to register an account directly via the embedded registry form within our application and/or website or you can use third-party authentication mechanisms.

These third-party providers are not linked with our company and hence you must check and read their privacy policies and other legally binding documents that rule their services.

By using third-party authentication mechanisms, you are allowing third-party applications and/or platforms to access some of your personal data, the relationship between you and the platform is outside any kind of control of our company.`
      },
      {
        title: "Warranties & Liability",
        content: `The content provided by our Services is provided to the user « as it is » and « as available », we cannot guarantee that the content provided will be exact, true, or error-free. The user accesses our content at its own risks.

We will not be held responsible if any content on our Services is inaccurate or mistaken.

Our company will not be liable in case of network disruption, viruses, outside access, fraudulent use of payment methods or any other kind or type of technical issue or fraudulent access.`
      },
      {
        title: "Content Moderation",
        content: `If our user uploads, posts or submits any type of content on the Services you represent to us that you have all the necessary legal rights to upload, post or submit such content.

You shall not publish, distribute or upload any content that is, abusive, fake news, obscene, pornographic, illegal.

In addition to that you shall not try to impersonate anyone else or use a fake identity in order to use, access or publish any content on our Services.

You shall not use our Services to transmit any kind of malware, viruses, crypto lockers, ransomware or spyware.

Users will not threaten or verbally abuse other users nor will they spam the Services. User will use respectfully language, you will not try to abuse or discriminate based on race, religion, nationality, sexual gender or preference, age, disability and so on. Hate speech is prohibited.

Our Company has the right to delete, modify, censor and delete a client's content or account if any of the rules above are violated. This will be done without any prior justification or notice. The client will not receive any compensation.`
      },
      {
        title: "Third-Party Links",
        content: `Some of the contents available on our website and/or application can include materials from third-parties and outside sources. Third-party links on our websites and/or applications can direct you to outside of our control websites that are not affiliated with us. We are not responsible nor liable for controlling or examining the content or accuracy of third-party websites or outside sources.

Hence we are not liable nor responsible for any damages or misuse while accessing third-party links or external links or sources on our website and/or application.

Please read carefully our privacy policy regarding how to deal with third-party privacy policy, terms and conditions and cookie policy.`
      },
      {
        title: "Governing Law & Contact",
        content: `The present T&C are ruled by Swiss Law.

Any issue arising from these T&C regarding, but not limited to, their validity, interpretation, execution, consequences and so on will be pleaded in front of the relevant jurisdiction.

The relevant jurisdiction is Switzerland.

Contact Information

If you have any question regarding these Terms and Conditions you can contact us directly at: info@lweb.ch.

Cancellation and refunds

If our User cancels his subscription, the cancellation will only occur for future charges associated with that subscription. You can notify us of your cancellation at any time and this cancellation will occur at the end of your current billing period.

You will not receive a refund for the current billing cycle, users will continue to have the same access and benefits of your products for the remainder of the current billing period.

You might be able to get a partial or a full refund depending on where you live and based on the applicable legislation and regulation.

Our Company reserves the right to issue refunds or credits at our sole discretion.

If IAP are made within our Services you must check the Store Terms and Conditions on how to manage and get your refund or cancellation. You can check their condition at https://support.apple.com/en-ph/HT204084 for Apple or at https://support.google.com/googleplay/answer/2479637?hl=en for Google.`
      }
    ]
  }

  return (
    <div className="min-h-screen" style={{ backgroundColor: '#faf5ff' }}>
      {/* Header */}
      <header className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center space-x-2">
              <img src="/images/app-icon.png" alt="BuyVoice App Icon" className="w-8 h-8 rounded-lg" />
              <span className="text-xl font-bold text-gray-900">BuyVoice</span>
            </Link>
            <Button variant="outline" asChild>
              <Link href="/" className="flex items-center space-x-2">
                <ArrowLeft className="w-4 h-4" />
                <span>Back to Home</span>
              </Link>
            </Button>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-16 text-center">
        <div className="max-w-4xl mx-auto">
          <div className="w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6" style={{ backgroundColor: '#f3e8ff' }}>
            <FileText className="w-8 h-8" style={{ color: '#7c3aed' }} />
          </div>
          <Badge className="mb-4 border-0" style={{ backgroundColor: '#f3e8ff', color: '#7c3aed' }}>
            {termsData.header.lastUpdated}
          </Badge>
          <h1 className="text-4xl md:text-5xl font-bold mb-4" style={{ color: '#4c1d95' }}>
            {termsData.header.title}
          </h1>
          <p className="text-xl mb-8" style={{ color: '#7c3aed' }}>
            {termsData.header.subtitle}
          </p>
        </div>
      </section>

      {/* Content Sections */}
      <section className="container mx-auto px-4 pb-16">
        <div className="max-w-4xl mx-auto space-y-8">
          {termsData.sections.map((section, index) => (
            <Card
              key={index}
              className="border-0 hover:shadow-xl transition-shadow bg-white"
              style={{ boxShadow: '0 1px 4px rgba(0, 0, 0, 0.05)' }}
            >
              <CardHeader>
                <CardTitle className="text-xl font-bold flex items-center space-x-3" style={{ color: '#1f2937' }}>
                  <span className="w-8 h-8 rounded-lg flex items-center justify-center text-sm font-bold text-white" style={{ backgroundColor: '#7c3aed' }}>
                    {index + 1}
                  </span>
                  <span>{section.title}</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="rounded-lg p-6" style={{ backgroundColor: '#faf5ff' }}>
                  <p className="leading-relaxed whitespace-pre-line" style={{ color: '#4b5563', fontSize: '15px', lineHeight: '22px' }}>
                    {section.content}
                  </p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t mt-16" style={{ backgroundColor: '#f3e8ff' }}>
        <div className="container mx-auto px-4 py-8">
          <div className="text-center" style={{ color: '#6b7280' }}>
            <p>© 2024 Lweb Schweiz. All rights reserved.</p>
            <div className="mt-4 space-x-4">
              <Link
                href="/"
                className="transition-colors duration-200 hover:opacity-80"
                style={{ color: '#6b7280' }}
              >
                Home
              </Link>
              <Link
                href="/privacy-policy"
                className="transition-colors duration-200 hover:opacity-80"
                style={{ color: '#6b7280' }}
              >
                Privacy Policy
              </Link>
              <Link
                href="/terms-of-service"
                className="transition-colors duration-200 hover:opacity-80"
                style={{ color: '#6b7280' }}
              >
                Terms of Service
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
